name: lint
on: push
jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - name: activate linter
        run: npm ci
        run: make lint